name: RebMadPictures
favicon: null
layout_spectrum: 0.907490226905793
typography_spectrum: 0.09790409100241959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8a8b85'
    - '#2a2b25'
    - '#835d86'
    - '#cfd0ca'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
